package com.chatter.forumservice.model;

import java.util.Set;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

/**
 * ChatterForum
 * @author coreym
 *
 * Represents a Forum object that gets created when an entity
 * adds the Chatter widget to a web entity (i.e. website, blog,
 * web publication, etc.). Represents the container for comments
 * and contains the following data attributes:
 * 
 * - forumId (String): auto generated unique hash/partition key
 * - createdBy (String): id of entity that generated Forum object
 * - timeStamp (Long): date time stamp represents when Forum was created
 * - title (String): title given to generated Forum object
 * - comments (Set<String>): hash set of unique ChatterComment 
 * 	 hash/partition keys for comments added to Forum.
 */
@DynamoDBTable(tableName = "Chatter_Forum")
public class ChatterForum {
	
	private String forumId;
	private String createdBy;
	private Long timeStamp;
	private String title;
	private Set<String> commentIds;
	
	public ChatterForum() { }

	@DynamoDBHashKey(attributeName = "forum_id")
	@DynamoDBAutoGeneratedKey
	public String getForumId() {
		return forumId;
	}

	public void setForumId(String forumId) {
		this.forumId = forumId;
	}

	@DynamoDBIndexHashKey(globalSecondaryIndexName = "created_by_index", attributeName = "created_by")
	public String getCreatedBy() {
		return createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@DynamoDBIndexRangeKey(globalSecondaryIndexName = "created_by_index", attributeName = "time_stamp")
	public Long getTimeStamp() {
		return timeStamp;
	}

	public void setTimeStamp(Long timeStamp) {
		this.timeStamp = timeStamp;
	}

	@DynamoDBIndexHashKey(globalSecondaryIndexName = "title_index", attributeName = "title")
	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@DynamoDBAttribute(attributeName = "comment_ids")
	public Set<String> getCommentIds() {
		return commentIds;
	}

	public void setCommentIds(Set<String> commentIds) {
		this.commentIds = commentIds;
	}
	
	@Override
	public String toString() {
		return new StringBuilder()
			.append("***** Chatter Forum object *****")
			.append("\nforum_id: ").append(this.forumId)
			.append("\ncreated_by: ").append(this.createdBy)
			.append("\ntime_stamp: ").append(this.timeStamp)
			.append("\ntitle: ").append(this.title)
			.append("\ncomment_cnt: ").append(this.commentIds.size())
			.toString();
	}
}
