package com.chatter.model;

import java.util.Set;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.S3Link;

/**
 * ChatterComment
 * @author coreym
 *
 * This class represents a Chatter comment object generated by users in a 
 * Chatter Forum instance. This class contains the following data attributes:
 * 
 * - commentId (String)
 * - createdBy (String)
 * - timeStamp (Long)
 * - parentForumId (String)
 * - replyIds (Set<String>)
 * - flagIds (Set<String>)
 * - concurCnt (int)
 * - commentAudioUrl (S3Link)
 */
@DynamoDBTable(tableName = "Chatter_Comment")
public class ChatterComment {
	
	private String commentId;
	private String createdBy;
	private Long timeStamp;
	private String parentForumId;
	private Set<String> replyIds;
	private Set<String> flagIds;
	private int concurCnt;
	private S3Link commentAudioUrl;
	
	public ChatterComment() {}

	@DynamoDBHashKey(attributeName = "comment_id")
	@DynamoDBAutoGeneratedKey
	public String getCommentId() {
		return commentId;
	}

	public void setCommentId(String commentId) {
		this.commentId = commentId;
	}

	@DynamoDBIndexHashKey(globalSecondaryIndexName = "created_by_index", attributeName = "created_by")
	public String getCreatedBy() {
		return createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@DynamoDBIndexRangeKey(globalSecondaryIndexName = "created_by_index", attributeName = "time_stamp")
	public Long getTimeStamp() {
		return timeStamp;
	}

	public void setTimeStamp(Long timeStamp) {
		this.timeStamp = timeStamp;
	}

	@DynamoDBIndexHashKey(globalSecondaryIndexName = "parent_forum_index", attributeName = "parent_forum_id")
	public String getParentForumId() {
		return parentForumId;
	}

	public void setParentForumId(String parentForumId) {
		this.parentForumId = parentForumId;
	}

	@DynamoDBAttribute(attributeName = "reply_ids")
	public Set<String> getReplyIds() {
		return replyIds;
	}

	public void setReplyIds(Set<String> replyIds) {
		this.replyIds = replyIds;
	}

	@DynamoDBAttribute(attributeName = "flag_ids")
	public Set<String> getFlagIds() {
		return flagIds;
	}

	public void setFlagIds(Set<String> flagIds) {
		this.flagIds = flagIds;
	}

	@DynamoDBAttribute(attributeName = "concur_cnt")
	public int getConcurCnt() {
		return concurCnt;
	}

	public void setConcurCnt(int concurCnt) {
		this.concurCnt = concurCnt;
	}

	@DynamoDBAttribute(attributeName = "comment_audio_url")
	public S3Link getCommentAudioUrl() {
		return commentAudioUrl;
	}

	public void setCommentAudioUrl(S3Link commentAudioUrl) {
		this.commentAudioUrl = commentAudioUrl;
	}
	
	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder()
			.append("***** Chatter Comment object *****")
			.append("\ncomment_id: ").append(this.commentId)
			.append("\ncreated_by: ").append(this.createdBy)
			.append("\ntime_stamp: ").append(this.timeStamp)
			.append("\nparent_forum_id: ").append(this.parentForumId)
			.append("\nreply_cnt: ").append(this.replyIds.size())
			.append("\nflag_cnt: ").append(this.flagIds.size())
			.append("\nconcur_cnt: ").append(this.concurCnt)
			.append("\ncomment_audio_url: ").append(this.commentAudioUrl.getUrl().getFile());
		return builder.toString();
	}
}
