package com.chatter.dbservice.model;

import java.util.Set;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

/**
 * ChatterComment
 * @author coreym
 *
 * This class represents a Chatter comment object generated by users in a 
 * Chatter Forum instance. This class contains the following data attributes:
 * 
 * - commentId (String)
 * - createdBy (String)
 * - timeStamp (Long)
 * - parentForumId (String)
 * - replyIds (Set<String>)
 * - flagIds (Set<String>)
 * - concurCnt (int)
 * - audioFileLink (S3Link)
 */
@DynamoDBTable(tableName = "Chatter_Comment")
public class ChatterComment {

	private String commentId;
	private String createdBy;
	private Long timeStamp;
	private String forumId;
	private Set<String> replyIds;
	private Set<String> flagIds;
	private int concurCnt;
	private String s3BucketName;
	private String s3KeyName;
	
	public ChatterComment() { }

	@DynamoDBHashKey(attributeName = "comment_id")
	@DynamoDBAutoGeneratedKey
	public String getCommentId() {
		return commentId;
	}

	public void setCommentId(String commentId) {
		this.commentId = commentId;
	}

	@DynamoDBIndexHashKey(globalSecondaryIndexName = "created_by_index", attributeName = "created_by")
	public String getCreatedBy() {
		return createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@DynamoDBIndexRangeKey(globalSecondaryIndexName = "created_by_index", attributeName = "time_stamp")
	public Long getTimeStamp() {
		return timeStamp;
	}

	public void setTimeStamp(Long timeStamp) {
		this.timeStamp = timeStamp;
	}

	@DynamoDBIndexHashKey(globalSecondaryIndexName = "forum_id_index", attributeName = "forum_id")
	public String getForumId() {
		return forumId;
	}

	public void setForumId(String forumId) {
		this.forumId = forumId;
	}

	@DynamoDBAttribute(attributeName = "replies")
	public Set<String> getReplyIds() {
		return replyIds;
	}

	public void setReplyIds(Set<String> replyIds) {
		this.replyIds = replyIds;
	}

	@DynamoDBAttribute(attributeName = "flags")
	public Set<String> getFlagIds() {
		return flagIds;
	}

	public void setFlagIds(Set<String> flagIds) {
		this.flagIds = flagIds;
	}

	@DynamoDBAttribute(attributeName = "concur_cnt")
	public int getConcurCnt() {
		return concurCnt;
	}

	public void setConcurCnt(int concurCnt) {
		this.concurCnt = concurCnt;
	}
	
	@DynamoDBAttribute(attributeName = "s3_bucket")
	public String getS3BucketName() {
		return s3BucketName;
	}
	
	public void setS3BucketName(String s3BucketName) {
		this.s3BucketName = s3BucketName;
	}
	
	@DynamoDBAttribute(attributeName = "s3_key")
	public String getS3KeyName() {
		return s3KeyName;
	}
	
	public void setS3KeyName(String s3KeyName) {
		this.s3KeyName = s3KeyName;
	}
	
	@Override
	public String toString() {
		return new StringBuilder()
			.append("***** Chatter Comment *****")
			.append("\ncomment_id: ").append(this.commentId)
			.append("\ncreated_by: ").append(this.createdBy)
			.append("\ntime_stamp: ").append(this.timeStamp)
			.append("\nforum_id: ").append(this.forumId)
			.append("\nreply_cnt: ").append(this.replyIds.size())
			.append("\nflag_cnt: ").append(this.flagIds.size())
			.append("\nconcur_cnt: ").append(this.concurCnt)
			.append("\nS3 Bucket: ").append(this.s3BucketName)
			.append("\nS3 Key: ").append(this.s3KeyName)
			.toString();
	}
}
